/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three';
import React, { useEffect, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import cloneGltf from '../../../../../Utils/Utils';
import PlayerModel from './PlayerModel';

export default function Player({ action, material, config, pivot = false }) {
  const clone = useRef();
  const model = useGLTF('/src/assets/models/foot.glb');

  useEffect(() => {
    clone.current = cloneGltf(model);
    clone.current.scene.traverse((child) => {
      if (child instanceof THREE.Mesh) {
        child.material = material;
      }
    });
  }, []);

  return (
    <>
      {clone.current && (
        <PlayerModel
          action={action}
          clone={clone}
          material={material}
          config={config}
          pivot={pivot}
        />
      )}
    </>
  );
}
